# Generated by Django 5.1.5 on 2025-01-28 21:03

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('casts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='director',
            name='created_at',
            field=models.DateField(auto_now_add=True, default='2025-01-01'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='director',
            name='is_available',
            field=models.BooleanField(db_index=True, default=True),
        ),
        migrations.AddField(
            model_name='director',
            name='updated_at',
            field=models.DateField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='director',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
    ]
